### ISSUE TITLE
[4] Monitroll client setup

### ISSUE THREAD

**Issue by danilo-p** [nosebit/monitroll-client#4]
- Flow
- Jest
- Babel
- React
- Stylus
- Eslint
- Webpack

**Comment by brunomacf** [comment]
@danilo-p ...the eslint that you mentioned

```yaml
env:
    browser: true
    commonjs: true
    es6: true
extends:
    - 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
    sourceType: module
globals:
    process: true
    __dirname: true
    config: true
plugins:
    - react
    - flowtype
rules:
    getter-return: error
    no-await-in-loop: error
    no-compare-neg-zero: error
    no-cond-assign: error
    no-console: error
    no-constant-condition: error
    no-control-regex: error
    debugger: error
    no-dupe-args: error
    no-dupe-keys: error
    no-duplicate-case: error
    no-empty: error
    no-empty-character-class: error
    no-ex-assign: error
    no-extra-boolean-cast: error
    no-extra-parens: error
    no-extra-semi: error
    no-func-assign: error
    no-inner-declarations: error
    no-invalid-regexp: error
    no-irregular-whitespace: error
    no-obj-calls: error
    no-prototype-builtins: error
    no-regex-spaces: error
    no-sparse-arrays: error
    no-template-curly-in-string: error
    no-unexpected-multiline: error
    no-unreachable: error
    no-unsafe-finally: error
    no-unsafe-negation: error
    use-isnan: error
    valid-jsdoc: error
    valid-typeof: error
    accessor-pairs: error
    array-callback-return: error
    block-scoped-var: error
    class-methods-use-this: error
    complexity: error
    consistent-return: error
    curly:
        - error
        - multi-or-nest
        - consistent
    default-case: error
    dot-location:
        - error
        - property
    dot-notation: error
    eqeqeq: error
    guard-for-in: error
    no-alert: error
    no-caller: error
    no-case-declarations: error
    no-div-regex: error
    no-else-return: error
    no-empty-function: error
    no-empty-pattern: error
    no-eq-null: error
    no-eval: error
    no-extend-native: error
    no-extra-bind: error
    no-extra-label: error
    no-fallthrough: error
    no-floating-decimal: error
    no-global-assign: error
    no-implicit-coercion: error
    no-implicit-globals: error
    no-implied-eval: error
    no-invalid-this: error
    no-iterator: error
    #no-labels: error
    no-lone-blocks: error
    no-loop-func: error
    no-magic-numbers: error
    no-multi-spaces: error
    no-multi-str: error
    no-new: error
    no-new-func: error
    no-new-wrappers: error
    no-octal: error
    no-octal-escape: error
    no-param-reassign: error
    no-proto: error
    no-redeclare: error
    no-restricted-properties: error
    no-return-assign:
        - error
        - always
    no-return-await: error
    no-script-url: error
    no-self-assign: error
    no-self-compare: error
    no-sequences: error
    no-throw-literal: error
    no-unmodified-loop-condition: error
    no-unused-expressions: error
    no-unused-labels: error
    no-useless-call: error
    no-useless-concat: error
    no-useless-escape: error
    no-useless-return: error
    no-void: error
    no-warning-comments: error
    no-with: error
    prefer-promise-reject-errors: error
    radix:
        - error
        - as-needed
    require-await: error
    vars-on-top: error
    wrap-iife:
        - error
        - inside
    yoda:
        - error
        - never
        -
            exceptRange: true
    no-catch-shadow: error
    no-delete-var: error
    no-label-var: error
    no-restricted-globals:
        - error
        - event
    no-shadow: error
    no-shadow-restricted-names: error
    no-undef: error
    no-undef-init: error
    no-undefined: error
    no-unused-vars: error
    no-use-before-define: error
    global-require: error
    

    indent:
        - error
        - 4
        -
            SwitchCase: 1
            VariableDeclarator: 1
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - double
    semi:
        - error
        - never
    no-console:
        - off
    no-unused-vars:
        - error
        - varsIgnorePattern: "styles"
    flowtype/require-parameter-type:
        - error
        -
            excludeArrowFunctions: true
    flowtype/require-valid-file-annotation:
        - error
        - never
    flowtype/define-flow-type:
        - error
    flowtype/space-before-type-colon:
        - error
        - always
    flowtype/space-after-type-colon:
        - error
    flowtype/use-flow-type: error

settings:
    flowtype:
        onlyFilesWithFlowAnnotation: false
```
